name: "CodePress Review"
description: "Automatic code review using AI models (OpenAI, Anthropic, Google, etc.) with inline PR comments"
author: "@quantfive"

branding:
  icon: "git-pull-request"
  color: "green"

inputs:
  github_token:
    description: "GitHub token for API access"
    required: true
    default: ${{ github.token }}

  model_provider:
    description: "AI model provider (openai, anthropic, gemini)"
    required: true
    default: "openai"

  model_name:
    description: "AI model name (e.g., gpt-4o, claude-3-sonnet-20240229, gemini-1.5-pro)"
    required: true
    default: "o4-mini"

  openai_api_key:
    description: "OpenAI API key (required if using OpenAI)"
    required: false

  anthropic_api_key:
    description: "Anthropic API key (required if using Anthropic)"
    required: false

  gemini_api_key:
    description: "Google Gemini API key (required if using Gemini)"
    required: false

  max_turns:
    description: "Maximum number of turns for the interactive agent"
    required: false
    default: "12"

  update_pr_description:
    description: "Whether to update the PR description with AI-generated summary (true/false)"
    required: false
    default: "true"

  debug:
    description: "Enable debug mode to show detailed console logs (true/false)"
    required: false
    default: "false"

  # Trigger configuration inputs
  run_on_pr_opened:
    description: "Run review when PR is opened (true/false)"
    required: false
    default: "true"

  run_on_pr_reopened:
    description: "Run review when PR is reopened (true/false)"
    required: false
    default: "true"

  run_on_review_requested:
    description: "Run review when re-review is requested from github-actions[bot] (true/false)"
    required: false
    default: "true"

  run_on_comment_trigger:
    description: "Run review when comments contain trigger phrase (true/false)"
    required: false
    default: "true"

  comment_trigger_phrase:
    description: "Phrase that triggers review in comments (e.g., '@codepress/review')"
    required: false
    default: "@codepress/review"

runs:
  using: "node20"
  main: "dist/index.js"
