name: Build and Deploy to Build Branch

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required by peaceiris/actions-gh-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Run linting and type check
      #   run: |
      #     pnpm run lint
      #     pnpm run type-check

      - name: Build project
        run: pnpm run build

      - name: Prepare publish directory
        run: |
          mkdir publish
          cp -r dist/ publish/
          cp action.yml publish/
          cp README.md publish/
          # Only copy the update-major-tag workflow to the build branch
          mkdir -p publish/.github/workflows
          cp .github/workflows/update-major-tag.yml publish/.github/workflows/

      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The branch to deploy the build artifacts to
          publish_branch: build
          # The directory to deploy
          publish_dir: ./publish
          # This creates a branch with a clean history containing only the build artifacts
          force_orphan: true
          # The commit message for the build branch
          commit_message: "Build: Update dist folder from main@${{ github.sha }}"
