# Example workflow for using the CodePress Review action
# Copy this to your repository's .github/workflows/ directory

name: CodePress Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CodePress Review
        uses: your-username/ai-code-review@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model_provider: "openai"
          model_name: "gpt-4o"
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}  # For Anthropic
          # gemini_api_key: ${{ secrets.GEMINI_API_KEY }}        # For Google
          max_chunk_size: 12
