name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

# Define common setup steps as YAML anchors
x-setup-steps: &setup-steps
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Install pnpm
    uses: pnpm/action-setup@v4
    with:
      version: latest

  - name: Set up Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 20
      cache: "pnpm"

  - name: Install dependencies
    run: pnpm install --frozen-lockfile

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      <<: *setup-steps
      - name: Run linting
        run: pnpm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      <<: *setup-steps
      - name: Run type check
        run: pnpm run type-check

  test:
    runs-on: ubuntu-latest
    steps:
      <<: *setup-steps
      - name: Run tests
        run: pnpm run test
